import 'dart:convert';

List<NotificationModel> parseNotificationModel(String src) => List<NotificationModel>.from(json.decode(src)["data"].map<NotificationModel>((json)
=> NotificationModel.fromJson(json)));

class NotificationModel {
  final String? senderId;
  final String senderName;
  final String userId;
  final bool isRead;
  final String descriptionEn;
  final String titleEn;
  final String descriptionAr;
  final String titleAr;
  final bool isNew;
  final int id;
  final DateTime createdDate;
  final DateTime? modifiedDate;
  final String? createdByNameId;
  final String? modifiedByNameId;
  final String? createdByName;
  final String? modifiedByName;

    String ? url;

  NotificationModel({
    this.senderId,
    required this.senderName,
    required this.userId,
    required this.isRead,
    required this.descriptionEn,
    required this.titleEn,
    required this.descriptionAr,
    required this.titleAr,
    required this.isNew,
    required this.id,
    required this.createdDate,
    this.modifiedDate,
    this.createdByNameId,
    this.modifiedByNameId,
    this.createdByName,
    this.modifiedByName,
    this.url,
  });

  factory NotificationModel.fromJson(Map<String, dynamic> json) {
    return NotificationModel(
      senderId: json['senderId'],
      senderName: json['senderName']??"",
      userId: json['userId'],
      isRead: json['isRead'],
      descriptionEn: json['descriptionEn']??"",
      titleEn: json['titleEn']??"",
      descriptionAr: json['descriptionAr']??"",
      titleAr: json['titleAr'],
      isNew: json['isNew'],
      id: json['id'],
      url: json['url'],
      createdDate: DateTime.parse(json['createdDate']),
      modifiedDate: json['modifiedDate'] != null ? DateTime.parse(json['modifiedDate']) : null,
      createdByNameId: json['createdByNameId'],
      modifiedByNameId: json['modifiedByNameId'],
      createdByName: json['createdByName'],
      modifiedByName: json['modifiedByName'],
    );
  }
}


List<NotificationModel> dummyInstallmentsNotifications = [
  NotificationModel(
    senderId:"3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: false,
    descriptionEn: "Your next installment for unit #45 is due on January 15, 2026. Amount: 5,000 EGP.",
    titleEn: "Installment Due Soon",
    descriptionAr: "القسط القادم للوحدة رقم 45 مستحق في 15 يناير 2026. المبلغ: ٥٠٠٠ جنيه.",
    titleAr: "قسط مستحق قريباً",
    isNew: true,
    id: 201,
    url: "assets/images/financeIcon.png",
    createdDate: DateTime.now().subtract(const Duration(hours: 6)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: false,
    descriptionEn: "We have successfully received your installment payment. Thank you!",
    titleEn: "Payment Received",
    descriptionAr: "تم استلام دفعة القسط الخاص بك بنجاح. شكراً لتعاونك!",
    titleAr: "تم استلام الدفعة",
    isNew: true,
    id: 202,
    url: "assets/images/financeIcon.png",
    createdDate: DateTime.now().subtract(const Duration(days: 1)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: true,
    descriptionEn: "Reminder: Your December installment is overdue. Please settle it to avoid penalties.",
    titleEn: "Overdue Installment",
    descriptionAr: "تذكير: قسط شهر ديسمبر متأخر. يرجى التسوية لتجنب الغرامات.",
    titleAr: "قسط متأخر",
    isNew: false,
    id: 203,
    url: "assets/images/financeIcon.png",
    createdDate: DateTime.now().subtract(const Duration(days: 15)),
    modifiedDate: DateTime.now().subtract(const Duration(days: 10)),
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: "Finance Dept",
  ),
  NotificationModel(
    senderId:"3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: false,
    descriptionEn: "Your next installment for unit #45 is due on January 15, 2026. Amount: 5,000 EGP.",
    titleEn: "Installment Due Soon",
    descriptionAr: "القسط القادم للوحدة رقم 45 مستحق في 15 يناير 2026. المبلغ: ٥٠٠٠ جنيه.",
    titleAr: "قسط مستحق قريباً",
    isNew: true,
    id: 201,
    url: "assets/images/financeIcon.png",
    createdDate: DateTime.now().subtract(const Duration(hours: 6)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: false,
    descriptionEn: "We have successfully received your installment payment. Thank you!",
    titleEn: "Payment Received",
    descriptionAr: "تم استلام دفعة القسط الخاص بك بنجاح. شكراً لتعاونك!",
    titleAr: "تم استلام الدفعة",
    isNew: true,
    id: 202,
    url: "assets/images/financeIcon.png",    createdDate: DateTime.now().subtract(const Duration(days: 1)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: true,
    descriptionEn: "Reminder: Your December installment is overdue. Please settle it to avoid penalties.",
    titleEn: "Overdue Installment",
    descriptionAr: "تذكير: قسط شهر ديسمبر متأخر. يرجى التسوية لتجنب الغرامات.",
    titleAr: "قسط متأخر",
    isNew: false,
    id: 203,
    url: "assets/images/financeIcon.png",    createdDate: DateTime.now().subtract(const Duration(days: 15)),
    modifiedDate: DateTime.now().subtract(const Duration(days: 10)),
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: "Finance Dept",
  ),
  NotificationModel(
    senderId:"3",
    senderName: "قسم المالية",
    userId: "123",
    isRead: false,
    descriptionEn: "Your next installment for unit #45 is due on January 15, 2026. Amount: 5,000 EGP.",
    titleEn: "Installment Due Soon",
    descriptionAr: "القسط القادم للوحدة رقم 45 مستحق في 15 يناير 2026. المبلغ: ٥٠٠٠ جنيه.",
    titleAr: "قسط مستحق قريباً",
    isNew: true,
    id: 201,
    url: "assets/images/financeIcon.png",
    createdDate: DateTime.now().subtract(const Duration(hours: 6)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Finance Dept",
    modifiedByName: null,
  ),

];

List<NotificationModel> dummyOccasionsNotifications = [
  NotificationModel(
    senderId: "1",
    senderName: "الإدارة",
    userId: "123",
    isRead: false,
    descriptionEn: "Happy New Year 2026! Wishing you a year full of joy, success, and prosperity.",
    titleEn: "Happy New Year",
    descriptionAr: "كل عام وأنتم بخير! عام جديد سعيد 2026 مليء بالفرح والنجاح والازدهار.",
    titleAr: "رأس السنة الميلادية",
    isNew: true,
    id: 101,
    url: "assets/images/eventsIcon.png",
    createdDate: DateTime(2026, 1, 1).subtract(const Duration(hours: 2)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Admin",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "1",
    senderName: "الإدارة",
    userId: "123",
    isRead: false,
    descriptionEn: "Eid al-Fitr Mubarak! May this blessed occasion bring you peace, happiness, and blessings.",
    titleEn: "Eid al-Fitr Mubarak",
    descriptionAr: "عيد الفطر المبارك! كل عام وأنتم بخير، تقبل الله طاعتكم وأدام عليكم الصحة والسعادة.",
    titleAr: "عيد الفطر المبارك",
    isNew: true,
    id: 102,
    url: "assets/images/eventsIcon.png",      createdDate: DateTime.now().subtract(const Duration(days: 3)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Admin",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "1",
    senderName: "الإدارة",
    userId: "123",
    isRead: true,
    descriptionEn: "Eid al-Adha Mubarak! May Allah accept your sacrifices and bless you abundantly.",
    titleEn: "Eid al-Adha Mubarak",
    descriptionAr: "عيد الأضحى المبارك! تقبل الله منا ومنكم، وكل عام وأنتم بخير.",
    titleAr: "عيد الأضحى المبارك",
    isNew: false,
    id: 103,
    url: "assets/images/eventsIcon.png",      createdDate: DateTime.now().subtract(const Duration(days: 10)),
    modifiedDate: DateTime.now().subtract(const Duration(days: 7)),
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Admin",
    modifiedByName: "Admin",
  ),
  NotificationModel(
    senderId: "2",
    senderName: "نظام الإشعارات",
    userId: "123",
    isRead: false,
    descriptionEn: "Happy Islamic New Year! May the Hijri year bring you peace and spiritual growth.",
    titleEn: "Hijri New Year",
    descriptionAr: "عام هجري جديد مبارك! كل عام وأنتم أقرب إلى الله، عام مليء بالبركة والخير.",
    titleAr: "رأس السنة الهجرية",
    isNew: true,
    id: 104,
    url: "assets/images/eventsIcon.png",      createdDate: DateTime.now().subtract(const Duration(days: 6)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "System",
    modifiedByName: null,
  ),
];
List<NotificationModel> dummyConstructionStageNotifications = [
  NotificationModel(
    senderId: "4",
    senderName: "إدارة المشروعات",
    userId: "123",
    isRead: false,
    descriptionEn: "The foundation stage for unit #45 has been completed successfully.",
    titleEn: "Foundation Completed",
    descriptionAr: "تم الانتهاء من مرحلة الأساسات للوحدة رقم 45 بنجاح.",
    titleAr: "الانتهاء من مرحلة الأساسات",
    isNew: true,
    id: 301,
    url: "assets/images/constructionIcon.png",
    createdDate: DateTime.now().subtract(const Duration(hours: 4)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Projects Dept",
    modifiedByName: null,

  ),
  NotificationModel(
    senderId: "4",
    senderName: "إدارة المشروعات",
    userId: "123",
    isRead: false,
    descriptionEn: "The structural framework for unit #45 is now 70% complete.",
    titleEn: "Construction Progress Update",
    descriptionAr: "تم إنجاز 70٪ من الهيكل الخرساني للوحدة رقم 45.",
    titleAr: "تحديث تقدم البناء",
    isNew: true,
    id: 302,
    url: "assets/images/constructionIcon.png",
    createdDate: DateTime.now().subtract(const Duration(days: 1)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Projects Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "4",
    senderName: "إدارة المشروعات",
    userId: "123",
    isRead: true,
    descriptionEn: "The finishing stage for unit #45 has started.",
    titleEn: "Finishing Stage Started",
    descriptionAr: "تم بدء مرحلة التشطيبات للوحدة رقم 45.",
    titleAr: "بدء مرحلة التشطيبات",
    isNew: false,
    id: 303,
    url: "assets/images/constructionIcon.png",
    createdDate: DateTime.now().subtract(const Duration(days: 10)),
    modifiedDate: DateTime.now().subtract(const Duration(days: 8)),
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Projects Dept",
    modifiedByName: "Projects Dept",
  ),
  NotificationModel(
    senderId: "4",
    senderName: "إدارة المشروعات",
    userId: "123",
    isRead: false,
    descriptionEn: "Electrical and plumbing works for unit #45 are underway.",
    titleEn: "MEP Works In Progress",
    descriptionAr: "أعمال الكهرباء والسباكة للوحدة رقم 45 قيد التنفيذ حالياً.",
    titleAr: "أعمال الكهرباء والسباكة",
    isNew: true,
    id: 304,
    url: "assets/images/constructionIcon.png",
    createdDate: DateTime.now().subtract(const Duration(hours: 12)),
    modifiedDate: null,
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Projects Dept",
    modifiedByName: null,
  ),
  NotificationModel(
    senderId: "4",
    senderName: "إدارة المشروعات",
    userId: "123",
    isRead: true,
    descriptionEn: "Unit #45 construction has reached the final inspection stage.",
    titleEn: "Final Inspection",
    descriptionAr: "وصلت أعمال بناء الوحدة رقم 45 إلى مرحلة المعاينة النهائية.",
    titleAr: "المعاينة النهائية",
    isNew: false,
    id: 305,
    url: "assets/images/constructionIcon.png",
    createdDate: DateTime.now().subtract(const Duration(days: 20)),
    modifiedDate: DateTime.now().subtract(const Duration(days: 18)),
    createdByNameId: null,
    modifiedByNameId: null,
    createdByName: "Projects Dept",
    modifiedByName: "Projects Dept",
  ),
];
